<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ToolsLibrary">
      <HintPath>..\ToolsLibrary\obj\Debug\net8.0\ToolsLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Collections" />
    <Using Include="System.Console">
      <Static>True</Static>
    </Using>
    <Using Include="System.Diagnostics" />
    <Using Include="System.Math">
      <Static>True</Static>
    </Using>
    <Using Include="System.Numerics" />
    <Using Include="System.Reflection" />
    <Using Include="System.Text" />
  </ItemGroup>

</Project>
